language: python
python:
  - '3.7'
  - '3.6'
#Install dependencies
install:
  - pip install numpy
  - pip install scipy
  - pip install tensorflow==2.0
  - python setup.py install
#Run the tests
script:
  - pytest